name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tar
        run: |
          tar -czvf  github.tar.gz .github
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: 版本发布
          draft: true
          body_path: Release.md
          files: github.tar.gz
