name: Push Trigger Project A Command

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - "projectB/**"

permissions:
  contents: read

jobs:
  command-execute:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: command
        run: |
          bash ${{github.workspace}}/projectA/projectA.sh
