name: Test Path Selector

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - projectA/*
      - projectC/*

permissions:
  contents: read

jobs:
  command-execute:
    runs-on: ubuntu-latest

    steps:
      - name: command
        run: |
          bash ${{ github.workflow }}/projectA/projectA.sh
