name: Test Scp File

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read

env:
  SERVER_USER: ec2-user
  SERVER_HOST: ec2-13-113-14-216.ap-northeast-1.compute.amazonaws.com
  SERVER_PORT: 22

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Packet Project
        run: |
          mkdir -p packet
          echo ${{ github.sha }} > packet/sha
          tar -czvf packet packet-${{ github.sha }}.tar.gz

      - name: Upload Packet
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          port: ${{ env.SERVER_PORT }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: packet-${{ github.sha }}.tar.gz
          target: .packet
