name: Test Scp File

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

env:
  SERVER_USER: ec2-user
  SERVER_HOST: ec2-13-113-14-216.ap-northeast-1.compute.amazonaws.com

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Packet Project
        run: |
          mkdir -p packet/A
          mkdir -p packet/B
          mkdir -p packet/C
          echo ${{ github.sha }} > packet/A/sha
          echo ${{ github.sha }} > packet/B/sha
          echo ${{ github.sha }} > packet/C/sha

      - name: Upload Packet
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: packet/A,packet/B,packet/C
          target: .packet
          debug: true
