name: Test Login Server

on:
  push:
    branches: [main]

env:
  SERVER_USER: "ec2-user"
  SERVER_HOST: ec2-13-113-14-216.ap-northeast-1.compute.amazonaws.com

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: whoami
