name: Test Login Server

on:
  push:
    branches: [main]

env:
  SERVER_USER: "ec2-user"
  SERVER_HOST: ec2-13-113-14-216.ap-northeast-1.compute.amazonaws.com

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Configure Server PEM File
        run: |
          mkdir -p .ssh/
          echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > .ssh/server.pem
          chmod 600 .ssh/server.pem

      - name: Test Server Login In
        run: |
          ssh -i .ssh/server.pem ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} "ls"
